
/**
 *
 * @author Matthias
 */
public class AppoointmentDlg extends javax.swing.JDialog {

    /**
     * Creates new form AppoointmentDlg
     */
    public AppoointmentDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfTag = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfMonat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfJahr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfStunde = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfMinute = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfText = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(7, 2));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Tag:");
        getContentPane().add(jLabel1);

        tfTag.setText("8");
        getContentPane().add(tfTag);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Monat:");
        getContentPane().add(jLabel2);

        tfMonat.setText("9");
        getContentPane().add(tfMonat);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Jahr:");
        getContentPane().add(jLabel3);

        tfJahr.setText("2014");
        getContentPane().add(tfJahr);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Stunde:");
        getContentPane().add(jLabel4);

        tfStunde.setText("8");
        getContentPane().add(tfStunde);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Minute:");
        getContentPane().add(jLabel5);

        tfMinute.setText("45");
        getContentPane().add(tfMinute);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Text");
        getContentPane().add(jLabel6);

        tfText.setText("POS1-Workshop");
        getContentPane().add(tfText);

        btAdd.setText("übernehmen");
        getContentPane().add(btAdd);

        btCancel.setText("abbrechen");
        getContentPane().add(btCancel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppoointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppoointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppoointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppoointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AppoointmentDlg dialog = new AppoointmentDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tfJahr;
    private javax.swing.JTextField tfMinute;
    private javax.swing.JTextField tfMonat;
    private javax.swing.JTextField tfStunde;
    private javax.swing.JTextField tfTag;
    private javax.swing.JTextField tfText;
    // End of variables declaration//GEN-END:variables
}
